[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "1.0"
libc = "0.2"

[dependencies.atk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "^0.6.0"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.javascriptcore-rs-sys]
git = "https://github.com/gtk-rs/javascriptcore-rs"
version = "0.1.1"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.6.0"

[dependencies.soup-sys]
git = "https://github.com/gtk-rs/soup-sys-rs"
version = "^0.6.0"

[features]
dox = []
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]
v2_18 = ["v2_16"]
v2_6 = []
v2_8 = ["v2_6"]

[lib]
name = "webkit2gtk_sys"

[package]
build = "build.rs"
license = "MIT"
links = "web_kit2"
name = "webkit2gtk-sys"
version = "0.6.0"
